//CONTENT
export const ADD: 'ADD' = 'ADD';
export const ADD_AT: 'ADD_AT' = 'ADD_AT';
export const ADD_BUN: 'ADD_BUN' = 'ADD_BUN';
export const REMOVE: 'REMOVE' = 'REMOVE';
export const CHANGE_ORDER: 'CHANGE_ORDER' = 'CHANGE_ORDER';

//CURRENT_INGREDIENT
export const SET_CURRENT_INGREDIENT: 'SET_CURRENT_INGREDIENT' = 'SET_CURRENT_INGREDIENT';
export const CLEAR_CURRENT_INGREDIENT: 'CLEAR_CURRENT_INGREDIENT' = 'CLEAR_CURRENT_INGREDIENT';

//DATA
export const SET_INGREDIENTS: 'SET_INGREDIENTS' = 'SET_INGREDIENTS';
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS: 'GET_INGREDIENTS' = 'GET_INGREDIENTS';
export const GET_INGREDIENTS_FAILED: 'GET_INGREDIENTS_FAILED' = 'GET_INGREDIENTS_FAILED';

//CURRENT_ORDER
export const GET_ORDER_ID: 'GET_ORDER_ID' = 'GET_ORDER_ID';
export const CLEAR_ORDER_ID: 'CLEAR_ORDER_ID' = 'CLEAR_ORDER_ID';
export const CLEAR_ORDER: 'CLEAR_ORDER' = 'CLEAR_ORDER';

//USER
export const SIGN_IN: 'SIGN_IN' = 'SIGN_IN';
export const SIGN_OUT: 'SIGN_OUT' = 'SIGN_OUT';
export const SIGN_IN_ERROR: 'SIGN_IN_ERROR' = 'SIGN_IN_ERROR';
export const GET_USER_INFO: 'GET_USER_INFO' = 'GET_USER_INFO';
export const SET_USER_INFO: 'SET_USER_INFO' = 'SET_USER_INFO';
export const REFRESH_TOKEN: 'REFRESH_TOKEN' = 'REFRESH_TOKEN';
export const AUTH_ERROR: 'AUTH_ERROR' = 'AUTH_ERROR';
export const RESET_REQUEST: 'RESET_REQUEST' = 'RESET_REQUEST';
export const RESET_REQUEST_SAVE: 'RESET_REQUEST_SAVE' = 'RESET_REQUEST_SAVE';

//SOCKETS
export const WS_CONNECTION_START: 'WS_CONNECTION_START' = 'WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';
export const WS_GET_MESSAGE: 'WS_GET_MESSAGE' = 'WS_GET_MESSAGE';
export const WS_SEND_MESSAGE: 'WS_SEND_MESSAGE' = 'WS_SEND_MESSAGE';
export const WS_CONNECTION_START_USER: 'WS_CONNECTION_START_USER' = 'WS_CONNECTION_START_USER';
export const WS_CONNECTION_SUCCESS_USER: 'WS_CONNECTION_SUCCESS_USER' = 'WS_CONNECTION_SUCCESS_USER';
export const WS_CONNECTION_ERROR_USER: 'WS_CONNECTION_ERROR_USER' = 'WS_CONNECTION_ERROR_USER';
export const WS_CONNECTION_CLOSED_USER: 'WS_CONNECTION_CLOSED_USER' = 'WS_CONNECTION_CLOSED_USER';
export const WS_GET_MESSAGE_USER: 'WS_GET_MESSAGE_USER' = 'WS_GET_MESSAGE_USER';
